### ISSUE TITLE
Bugfix when unliking a Movie

### ISSUE THREAD

**Issue by tschaengguu** [PythonDataScience24/group_27_movie_recom#5]
First of all, The installation guide is structured **very good and clear**. Also the GUI seems to be very cool, considering the Time you had to implement it. **Cool :)**

After testing your GUI, i stumbled over an error when trying to Unlike an error.

Steps to reproduce:
- Search for "James Bond"
- Like "Jatt James Bond 2014".
- Unlike "Jatt James Bond 2014".

Tried to find a simple solution, but without knowing the detailed structured, it is not that easy to find.

**Comment by piskel** [comment]
Should be fixed
